# Generated by Django 5.0.6 on 2024-05-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('fecha_fundacion', models.DateField()),
                ('normas', models.FileField(blank=True, null=True, upload_to='normas/')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('ano_publicacion', models.DateField()),
                ('editorial', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('numero_ejemplares', models.IntegerField()),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrabajoFinal.biblioteca')),
            ],
        ),
    ]
