# Generated by Django 5.0.6 on 2024-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrabajoFinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='numero_ejemplares',
            new_name='numero_de_ejemplares',
        ),
    ]
